//! Shared credential types, JSON helpers, and the async message-based
//! `IssuerDriver` UniFFI callback interface for the host-mediated Issuers SDK
//! experiment.
//!
//! ## Design
//!
//! Two traits serve different audiences:
//!
//! * **[`IssuerDriver`]** — the *UniFFI* callback interface.  Foreign-language
//!   hosts (Python, Swift, Kotlin) implement exactly one async method:
//!   `handle_message(msg: IssuerMsg) -> Result<IssuerValue, SdkError>`.
//!   Because it is async, Python adapters become trivial single-line delegates
//!   (`return await self._inner.handle_message(msg)`) — all routing happens in
//!   Rust.
//!
//! * **[`Issuer`]** — the ergonomic *Rust* trait.  Rust crates (`orb-kit`,
//!   `nfc-kit`) implement typed async methods like `fetch_credential`.
//!   A blanket `impl<T: Issuer> IssuerDriver for T` dispatches incoming
//!   [`IssuerMsg`]s to the right method and wraps the result in the
//!   appropriate [`IssuerValue`] variant.
//!
//! ## Async trait mechanics
//!
//! Both traits use native async fn syntax (stable since Rust 1.75, available
//! here on 1.94).  No `async-trait` proc-macro is needed for our definitions
//! or the blanket impl.  However, the code generated by
//! `uniffi::setup_scaffolding!` for the `#[uniffi::export(with_foreign)]`
//! callback handler *does* emit `#[::async_trait::async_trait]` on the
//! auto-generated `UniFfiCallbackHandlerIssuerDriver` struct, so `async-trait`
//! must be a direct dependency of this crate.
//!
//! ## UniFFI scaffolding
//!
//! `issuer-sdk` owns `uniffi::setup_scaffolding!("issuer_sdk")` and is
//! compiled as `cdylib + rlib`.  Dependent cdylibs (`issuer-host`) call
//! `issuer_sdk::uniffi_reexport_scaffolding!()` to include these symbols.

use serde::{Deserialize, Serialize};
use thiserror::Error;

// ──────────────────────────────────────────────────────────────────────────────
// Domain types
// ──────────────────────────────────────────────────────────────────────────────

/// Request sent from the host to a credential issuer.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CredentialRequest {
    /// Opaque identifier for the credential subject (nullifier hash stub).
    pub user_id: String,
}

/// Credential returned by an issuer (SD-JWT stub for the demo).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Credential {
    pub id: String,
    pub issuer: String,
    pub data: String,
}

// ──────────────────────────────────────────────────────────────────────────────
// Error type
// ──────────────────────────────────────────────────────────────────────────────

/// Errors surfaced through the `IssuerDriver` FFI boundary.
#[derive(Debug, Clone, PartialEq, Eq, Error, uniffi::Error)]
#[uniffi(flat_error)]
pub enum SdkError {
    #[error("invalid json: {0}")]
    InvalidJson(String),
    #[error("user_id must not be empty")]
    EmptyUserId,
    #[error("issuance failed: {0}")]
    IssuanceFailed(String),
    /// Returned when a handler receives a message variant it does not recognise.
    /// Included for forward-compatibility as the message enum grows.
    #[error("unsupported message: {0}")]
    UnsupportedMessage(String),
}

// ──────────────────────────────────────────────────────────────────────────────
// Message protocol
// ──────────────────────────────────────────────────────────────────────────────

/// All issuer operations encoded as enum variants.
///
/// The host constructs one of these and passes it to
/// [`IssuerDriver::handle_message`].  New operations only require new variants
/// here and in [`IssuerValue`]; the FFI surface stays stable.
#[derive(Debug, Clone, uniffi::Enum)]
pub enum IssuerMsg {
    /// Fetch a credential for the JSON-serialised [`CredentialRequest`].
    FetchCredential { request_json: String },
}

/// All issuer return values encoded as enum variants.
#[derive(Debug, Clone, uniffi::Enum)]
pub enum IssuerValue {
    /// A successfully issued credential, JSON-serialised.
    Credential { json: String },
}

// ──────────────────────────────────────────────────────────────────────────────
// IssuerDriver — async UniFFI callback interface (foreign-language path)
// ──────────────────────────────────────────────────────────────────────────────

/// Async single-method UniFFI callback interface.
///
/// Because this method is async, foreign adapters (Python, Swift, Kotlin) can
/// delegate directly to the issuer's own async method without any synchronous
/// bridging:
///
/// ```python
/// async def handle_message(self, msg):
///     return await self._inner.handle_message(msg)
/// ```
///
/// All routing (which [`IssuerMsg`] variant → which operation) happens inside
/// the Rust blanket impl.
/// Async single-method UniFFI callback interface.
///
/// Because this method is async, foreign adapters (Python, Swift, Kotlin) can
/// delegate directly to the issuer's own async `handle_message` method — all
/// routing happens inside the Rust blanket impl, not in the adapter.
///
/// Order matters: `#[uniffi::export(with_foreign)]` must come BEFORE
/// `#[async_trait::async_trait]`.  UniFFI processes the trait first (seeing the
/// native `async fn`), generates its vtable machinery, then `async_trait` makes
/// the trait dyn-compatible by boxing the futures.  This is the same pattern
/// used by `HttpClient` and `OxideBackupManager` in the oxide crate.
#[uniffi::export(with_foreign)]
#[async_trait::async_trait]
pub trait IssuerDriver: Send + Sync {
    async fn handle_message(&self, msg: IssuerMsg) -> Result<IssuerValue, SdkError>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Issuer — ergonomic async Rust trait (native path)
// ──────────────────────────────────────────────────────────────────────────────

/// Ergonomic Rust trait for issuer implementations.
///
/// Rust crates implement typed async methods here.  The blanket impl below
/// automatically satisfies [`IssuerDriver`], so implementors never write
/// message-dispatch code.
/// Ergonomic Rust trait for issuer implementations.
///
/// Rust crates implement typed async methods here.  The blanket impl below
/// automatically satisfies [`IssuerDriver`], so implementors never write
/// message-dispatch code.
#[async_trait::async_trait]
pub trait Issuer: Send + Sync {
    async fn fetch_credential(&self, request_json: String) -> Result<String, SdkError>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Blanket impl: Issuer → IssuerDriver
// ──────────────────────────────────────────────────────────────────────────────

/// Any [`Issuer`] automatically satisfies [`IssuerDriver`].
///
/// Both traits are defined in this crate, satisfying the orphan rule.
/// Incoming [`IssuerMsg`] variants are matched and dispatched to the
/// appropriate [`Issuer`] method; results are wrapped in [`IssuerValue`].
/// Any [`Issuer`] automatically satisfies [`IssuerDriver`].
///
/// Both traits live in this crate, satisfying the orphan rule.  `#[async_trait]`
/// is applied to match the `async_trait`-annotated `IssuerDriver` definition.
#[async_trait::async_trait]
impl<T: Issuer + Send + Sync> IssuerDriver for T {
    async fn handle_message(&self, msg: IssuerMsg) -> Result<IssuerValue, SdkError> {
        match msg {
            IssuerMsg::FetchCredential { request_json } => self
                .fetch_credential(request_json)
                .await
                .map(|json| IssuerValue::Credential { json }),
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// JSON helpers
// ──────────────────────────────────────────────────────────────────────────────

pub fn to_json<T: Serialize>(value: &T) -> Result<String, SdkError> {
    serde_json::to_string(value).map_err(|e| SdkError::InvalidJson(e.to_string()))
}

pub fn validate_request(request: &CredentialRequest) -> Result<(), SdkError> {
    if request.user_id.trim().is_empty() {
        return Err(SdkError::EmptyUserId);
    }
    Ok(())
}

pub fn parse_request_json(json: &str) -> Result<CredentialRequest, SdkError> {
    let request: CredentialRequest =
        serde_json::from_str(json).map_err(|e| SdkError::InvalidJson(e.to_string()))?;
    validate_request(&request)?;
    Ok(request)
}

pub fn build_credential_json(id: &str, issuer: &str, data: String) -> Result<String, SdkError> {
    to_json(&Credential {
        id: id.to_string(),
        issuer: issuer.to_string(),
        data,
    })
}

// ──────────────────────────────────────────────────────────────────────────────
// UniFFI scaffolding
// ──────────────────────────────────────────────────────────────────────────────

// Also generates `uniffi_reexport_scaffolding!()` for dependent cdylibs.
uniffi::setup_scaffolding!("issuer_sdk");

// ──────────────────────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    struct EchoIssuer;

    #[async_trait::async_trait]
    impl Issuer for EchoIssuer {
        async fn fetch_credential(&self, request_json: String) -> Result<String, SdkError> {
            let req = parse_request_json(&request_json)?;
            build_credential_json("test-id", "echo", req.user_id)
        }
    }

    #[test]
    fn parses_valid_request() {
        let req = parse_request_json(r#"{"user_id":"user-abc"}"#).unwrap();
        assert_eq!(req.user_id, "user-abc");
    }

    #[test]
    fn rejects_blank_user_id() {
        assert_eq!(
            parse_request_json(r#"{"user_id":"   "}"#).unwrap_err(),
            SdkError::EmptyUserId
        );
    }

    #[test]
    fn rejects_empty_user_id() {
        assert_eq!(
            parse_request_json(r#"{"user_id":""}"#).unwrap_err(),
            SdkError::EmptyUserId
        );
    }

    #[test]
    fn builds_credential_json() {
        let json = build_credential_json("cred-1", "orb-kit", "stub".to_string()).unwrap();
        let cred: Credential = serde_json::from_str(&json).unwrap();
        assert_eq!(cred.issuer, "orb-kit");
    }

    #[tokio::test]
    async fn issuer_fetch_credential_works() {
        let json = EchoIssuer
            .fetch_credential(r#"{"user_id":"user-abc"}"#.to_string())
            .await
            .unwrap();
        let cred: Credential = serde_json::from_str(&json).unwrap();
        assert_eq!(cred.issuer, "echo");
        assert_eq!(cred.data, "user-abc");
    }

    #[tokio::test]
    async fn blanket_dispatches_fetch_credential() {
        let driver: &dyn IssuerDriver = &EchoIssuer;
        let result = driver
            .handle_message(IssuerMsg::FetchCredential {
                request_json: r#"{"user_id":"blanket-user"}"#.to_string(),
            })
            .await
            .unwrap();
        let IssuerValue::Credential { json } = result;
        let cred: Credential = serde_json::from_str(&json).unwrap();
        assert_eq!(cred.data, "blanket-user");
    }

    #[tokio::test]
    async fn blanket_propagates_sdk_error() {
        let driver: &dyn IssuerDriver = &EchoIssuer;
        let err = driver
            .handle_message(IssuerMsg::FetchCredential {
                request_json: r#"{"user_id":""}"#.to_string(),
            })
            .await
            .unwrap_err();
        assert_eq!(err, SdkError::EmptyUserId);
    }

    #[test]
    fn unsupported_message_error_formats() {
        let err = SdkError::UnsupportedMessage("WeirdOp".to_string());
        assert!(err.to_string().contains("WeirdOp"));
    }
}
