/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsHello = Hello
export class Hello {
  constructor()
  echo(query: string): Promise<string>
  sayHello(): string
}
