#ifndef WALLETKIT_CORE_FFI_H
#define WALLETKIT_CORE_FFI_H

/* Generated by cbindgen from crates/walletkit/src/native/c. Do not edit. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// A cancellation token for one async call.
typedef struct WalletKitOperationHandle {
  // Registry ID.
  uint64_t id;
} WalletKitOperationHandle;

// Bytes owned by Rust. Only `walletkit_buffer_free` may release them.
typedef struct WalletKitBuffer {
  // First byte, or null for an absent value.
  uint8_t *data;
  // Length in bytes.
  size_t len;
} WalletKitBuffer;

// Borrowed bytes. `data` may be null only when `len` is zero.
typedef struct WalletKitByteSlice {
  // First byte.
  const uint8_t *data;
  // Length in bytes.
  size_t len;
} WalletKitByteSlice;

// An `Authenticator`.
typedef struct WalletKitAuthenticatorHandle {
  // Registry ID.
  uint64_t id;
} WalletKitAuthenticatorHandle;

// An unsigned 256-bit integer as 32 big-endian bytes.
typedef struct WalletKitUint256 {
  // Big-endian bytes.
  uint8_t bytes[32];
} WalletKitUint256;

// A `FieldElement`.
typedef struct WalletKitFieldElementHandle {
  // Registry ID.
  uint64_t id;
} WalletKitFieldElementHandle;

// A `ProofRequest`.
typedef struct WalletKitProofRequestHandle {
  // Registry ID.
  uint64_t id;
} WalletKitProofRequestHandle;

// A `ProofResponse`.
typedef struct WalletKitProofResponseHandle {
  // Registry ID.
  uint64_t id;
} WalletKitProofResponseHandle;

// An `OwnershipProof`.
typedef struct WalletKitOwnershipProofHandle {
  // Registry ID.
  uint64_t id;
} WalletKitOwnershipProofHandle;

// A `WalletKitZkArtifactSource`.
typedef struct WalletKitZkArtifactSourceHandle {
  // Registry ID.
  uint64_t id;
} WalletKitZkArtifactSourceHandle;

// A `CredentialStore`.
typedef struct WalletKitCredentialStoreHandle {
  // Registry ID.
  uint64_t id;
} WalletKitCredentialStoreHandle;

// An `InitializingAuthenticator`.
typedef struct WalletKitInitializingAuthenticatorHandle {
  // Registry ID.
  uint64_t id;
} WalletKitInitializingAuthenticatorHandle;

// An `EmbeddedZkArtifacts`.
typedef struct WalletKitEmbeddedZkArtifactsHandle {
  // Registry ID.
  uint64_t id;
} WalletKitEmbeddedZkArtifactsHandle;

// A `StoragePaths`.
typedef struct WalletKitStoragePathsHandle {
  // Registry ID.
  uint64_t id;
} WalletKitStoragePathsHandle;

// A `CachingZkArtifacts`.
typedef struct WalletKitCachingZkArtifactsHandle {
  // Registry ID.
  uint64_t id;
} WalletKitCachingZkArtifactsHandle;

// Signs request digests with the key certified by a session token.
typedef struct WalletKitRequestDigestSignerCallbacks {
  // Host state passed to every function.
  void *context;
  // Signs exactly 32 bytes, writing the platform signature to `out`.
  bool (*sign_digest)(void *context,
                      struct WalletKitByteSlice client_data_hash,
                      struct WalletKitBuffer *out);
  // Releases `context`. Called exactly once.
  void (*release)(void *context);
} WalletKitRequestDigestSignerCallbacks;

// A `VerifiedMatchToken`.
typedef struct WalletKitVerifiedMatchTokenHandle {
  // Registry ID.
  uint64_t id;
} WalletKitVerifiedMatchTokenHandle;

// A `FlamingoMatcher`.
typedef struct WalletKitFlamingoMatcherHandle {
  // Registry ID.
  uint64_t id;
} WalletKitFlamingoMatcherHandle;

// Supplies request-integrity sessions for attested Flamingo connections.
typedef struct WalletKitRequestIntegrityProviderCallbacks {
  // Host state passed to every function.
  void *context;
  // Starts preparing a session. The host must later call exactly one of
  // `walletkit_request_integrity_prepared` or `walletkit_request_integrity_failed`
  // with `completion`, from any thread.
  void (*prepare)(void *context,
                  uint64_t completion);
  // Releases `context`. Called exactly once.
  void (*release)(void *context);
} WalletKitRequestIntegrityProviderCallbacks;

// A `Credential`.
typedef struct WalletKitCredentialHandle {
  // Registry ID.
  uint64_t id;
} WalletKitCredentialHandle;

// A `UserAgent`.
typedef struct WalletKitUserAgentHandle {
  // Registry ID.
  uint64_t id;
} WalletKitUserAgentHandle;

// A `UserAgentBuilder`.
typedef struct WalletKitUserAgentBuilderHandle {
  // Registry ID.
  uint64_t id;
} WalletKitUserAgentBuilderHandle;

// A log sink. `level` is the `LogLevel` ordinal; messages are UTF-8.
typedef struct WalletKitLoggerCallbacks {
  // Host state passed to every function.
  void *context;
  // Receives one log message.
  void (*log)(void *context,
              uint8_t level,
              struct WalletKitByteSlice message);
  // Releases `context`. Called exactly once.
  void (*release)(void *context);
} WalletKitLoggerCallbacks;

// A `TfhNfcIssuer`.
typedef struct WalletKitTfhNfcIssuerHandle {
  // Registry ID.
  uint64_t id;
} WalletKitTfhNfcIssuerHandle;

// A `RecoveryBindingManager`.
typedef struct WalletKitRecoveryBindingManagerHandle {
  // Registry ID.
  uint64_t id;
} WalletKitRecoveryBindingManagerHandle;

// A device keystore. On failure a function returns `false` and may write an encoded
// `StorageError` to `out_error`; any other failure is reported as `HostFailure`.
typedef struct WalletKitDeviceKeystoreCallbacks {
  // Host state passed to every function.
  void *context;
  // Seals `plaintext` bound to `associated_data`.
  bool (*seal)(void *context,
               struct WalletKitByteSlice associated_data,
               struct WalletKitByteSlice plaintext,
               struct WalletKitBuffer *out,
               struct WalletKitBuffer *out_error);
  // Opens `ciphertext` bound to `associated_data`.
  bool (*open_sealed)(void *context,
                      struct WalletKitByteSlice associated_data,
                      struct WalletKitByteSlice ciphertext,
                      struct WalletKitBuffer *out,
                      struct WalletKitBuffer *out_error);
  // Releases `context`. Called exactly once.
  void (*release)(void *context);
} WalletKitDeviceKeystoreCallbacks;

// Atomic blob storage. Same error contract as [`DeviceKeystoreCallbacks`].
typedef struct WalletKitAtomicBlobStoreCallbacks {
  // Host state passed to every function.
  void *context;
  // Reads a blob, leaving `out` null when it does not exist.
  bool (*read)(void *context,
               struct WalletKitByteSlice path,
               struct WalletKitBuffer *out,
               struct WalletKitBuffer *out_error);
  // Atomically replaces a blob.
  bool (*write_atomic)(void *context,
                       struct WalletKitByteSlice path,
                       struct WalletKitByteSlice bytes,
                       struct WalletKitBuffer *out_error);
  // Deletes a blob.
  bool (*delete_blob)(void *context,
                      struct WalletKitByteSlice path,
                      struct WalletKitBuffer *out_error);
  // Releases `context`. Called exactly once.
  void (*release)(void *context);
} WalletKitAtomicBlobStoreCallbacks;

// A listener notified after vault changes.
typedef struct WalletKitVaultChangedListenerCallbacks {
  // Host state passed to every function.
  void *context;
  // Called after the vault changed.
  void (*on_vault_changed)(void *context);
  // Releases `context`. Called exactly once.
  void (*release)(void *context);
} WalletKitVaultChangedListenerCallbacks;

// A listener notified after activity changes.
typedef struct WalletKitActivityChangedListenerCallbacks {
  // Host state passed to every function.
  void *context;
  // Called after the activity history changed.
  void (*on_activity_changed)(void *context);
  // Releases `context`. Called exactly once.
  void (*release)(void *context);
} WalletKitActivityChangedListenerCallbacks;

// An `AddressBook`.
typedef struct WalletKitAddressBookHandle {
  // Registry ID.
  uint64_t id;
} WalletKitAddressBookHandle;

// A `ProofContext`.
typedef struct WalletKitProofContextHandle {
  // Registry ID.
  uint64_t id;
} WalletKitProofContextHandle;

// A `WorldId`.
typedef struct WalletKitWorldIdHandle {
  // Registry ID.
  uint64_t id;
} WalletKitWorldIdHandle;

// A `ProofOutput`.
typedef struct WalletKitProofOutputHandle {
  // Registry ID.
  uint64_t id;
} WalletKitProofOutputHandle;

// A `MerkleTreeProof`.
typedef struct WalletKitMerkleTreeProofHandle {
  // Registry ID.
  uint64_t id;
} WalletKitMerkleTreeProofHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The native interface version; the SDK refuses to run against another version.
uint32_t walletkit_abi_version(void);

// Creates a cancellation token for one async call. Release it with
// `walletkit_object_release` once the call has returned.
//
// # Safety
// `out` and `out_error` must be valid for writes.
bool walletkit_operation_new(struct WalletKitOperationHandle *out,
                             struct WalletKitBuffer *out_error);

// Cancels an operation before or during its call. Unknown handles are ignored.
void walletkit_operation_cancel(struct WalletKitOperationHandle operation);

// Releases a handle of any type. Idempotent; running calls keep their own references.
void walletkit_object_release(uint64_t id);

// Copies host bytes into a buffer that Rust can take ownership of, such as callback
// output. Returns an empty buffer when `data` is null.
//
// # Safety
// `data` must be readable for `len` bytes.
struct WalletKitBuffer walletkit_buffer_copy(const uint8_t *data,
                                             size_t len);

// Zeroes and releases a buffer returned by this library. Null buffers are ignored.
//
// # Safety
// `buffer` must come from this library and must not be used afterwards.
void walletkit_buffer_free(struct WalletKitBuffer buffer);

// `WalletKit.validateAuthenticatorPubkey`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_validate_authenticator_pubkey(struct WalletKitByteSlice authenticator_pubkey,
                                             struct WalletKitBuffer *out,
                                             struct WalletKitBuffer *out_error);

// `WalletKit.recoveryDataFromSeed`.
//
// Writes the binary encoding to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_recovery_data_from_seed(struct WalletKitByteSlice seed,
                                       struct WalletKitBuffer *out,
                                       struct WalletKitBuffer *out_error);

// `Authenticator.initStorage`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_init_storage(struct WalletKitAuthenticatorHandle authenticator,
                                          uint64_t now,
                                          struct WalletKitBuffer *out_error);

// `Authenticator.destroyStorage`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_destroy_storage(struct WalletKitAuthenticatorHandle authenticator,
                                             struct WalletKitBuffer *out_error);

// `Authenticator.packedAccountData`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_packed_account_data(struct WalletKitAuthenticatorHandle authenticator,
                                                 struct WalletKitUint256 *out,
                                                 struct WalletKitBuffer *out_error);

// `Authenticator.leafIndex`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_leaf_index(struct WalletKitAuthenticatorHandle authenticator,
                                        uint64_t *out,
                                        struct WalletKitBuffer *out_error);

// `Authenticator.onchainAddress`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_onchain_address(struct WalletKitAuthenticatorHandle authenticator,
                                             struct WalletKitBuffer *out,
                                             struct WalletKitBuffer *out_error);

// `Authenticator.getPackedAccountDataRemote`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_get_packed_account_data_remote(struct WalletKitOperationHandle operation,
                                                            struct WalletKitAuthenticatorHandle authenticator,
                                                            struct WalletKitUint256 *out,
                                                            struct WalletKitBuffer *out_error);

// `Authenticator.generateCredentialBlindingFactorRemote`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_generate_credential_blinding_factor_remote(struct WalletKitOperationHandle operation,
                                                                        struct WalletKitAuthenticatorHandle authenticator,
                                                                        uint64_t issuer_schema_id,
                                                                        struct WalletKitFieldElementHandle *out,
                                                                        struct WalletKitBuffer *out_error);

// `Authenticator.computeCredentialSub`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_compute_credential_sub(struct WalletKitAuthenticatorHandle authenticator,
                                                    struct WalletKitFieldElementHandle blinding_factor,
                                                    struct WalletKitFieldElementHandle *out,
                                                    struct WalletKitBuffer *out_error);

// `Authenticator.dangerSignChallenge`.
//
// Writes the bytes to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_danger_sign_challenge(struct WalletKitAuthenticatorHandle authenticator,
                                                   struct WalletKitByteSlice challenge,
                                                   struct WalletKitBuffer *out,
                                                   struct WalletKitBuffer *out_error);

// `Authenticator.dangerSignInitiateRecoveryAgentUpdate`.
//
// Writes the binary encoding to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_danger_sign_initiate_recovery_agent_update(struct WalletKitOperationHandle operation,
                                                                        struct WalletKitAuthenticatorHandle authenticator,
                                                                        struct WalletKitByteSlice new_recovery_agent,
                                                                        struct WalletKitBuffer *out,
                                                                        struct WalletKitBuffer *out_error);

// `Authenticator.updateRecoveryAgent`.
//
// Writes the UTF-8 string to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_update_recovery_agent(struct WalletKitOperationHandle operation,
                                                   struct WalletKitAuthenticatorHandle authenticator,
                                                   struct WalletKitByteSlice new_recovery_agent,
                                                   struct WalletKitBuffer *out,
                                                   struct WalletKitBuffer *out_error);

// `Authenticator.revertRecoveryAgentUpdate`.
//
// Writes the UTF-8 string to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_revert_recovery_agent_update(struct WalletKitOperationHandle operation,
                                                          struct WalletKitAuthenticatorHandle authenticator,
                                                          struct WalletKitBuffer *out,
                                                          struct WalletKitBuffer *out_error);

// `Authenticator.insertAuthenticator`.
//
// Writes the UTF-8 string to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_insert_authenticator(struct WalletKitOperationHandle operation,
                                                  struct WalletKitAuthenticatorHandle authenticator,
                                                  struct WalletKitByteSlice new_authenticator_pubkey,
                                                  struct WalletKitByteSlice new_authenticator_address,
                                                  struct WalletKitBuffer *out,
                                                  struct WalletKitBuffer *out_error);

// `Authenticator.hasAuthenticatorPubkey`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_has_authenticator_pubkey(struct WalletKitOperationHandle operation,
                                                      struct WalletKitAuthenticatorHandle authenticator,
                                                      struct WalletKitByteSlice authenticator_pubkey,
                                                      bool *out,
                                                      struct WalletKitBuffer *out_error);

// `Authenticator.getAuthenticatorPubkeys`.
//
// Writes the binary encoding to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_get_authenticator_pubkeys(struct WalletKitOperationHandle operation,
                                                       struct WalletKitAuthenticatorHandle authenticator,
                                                       struct WalletKitBuffer *out,
                                                       struct WalletKitBuffer *out_error);

// `Authenticator.removeAuthenticator`.
//
// Writes the UTF-8 string to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_remove_authenticator(struct WalletKitOperationHandle operation,
                                                  struct WalletKitAuthenticatorHandle authenticator,
                                                  struct WalletKitByteSlice authenticator_address,
                                                  uint32_t pubkey_id,
                                                  struct WalletKitByteSlice expected_authenticator_pubkey,
                                                  struct WalletKitBuffer *out,
                                                  struct WalletKitBuffer *out_error);

// `Authenticator.pollStatus`.
//
// Writes the binary encoding to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_poll_status(struct WalletKitOperationHandle operation,
                                         struct WalletKitAuthenticatorHandle authenticator,
                                         struct WalletKitByteSlice request_id,
                                         struct WalletKitBuffer *out,
                                         struct WalletKitBuffer *out_error);

// `Authenticator.generateProof`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_generate_proof(struct WalletKitOperationHandle operation,
                                            struct WalletKitAuthenticatorHandle authenticator,
                                            struct WalletKitProofRequestHandle proof_request,
                                            const uint64_t *now,
                                            struct WalletKitProofResponseHandle *out,
                                            struct WalletKitBuffer *out_error);

// `Authenticator.proveCredentialSub`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_prove_credential_sub(struct WalletKitOperationHandle operation,
                                                  struct WalletKitAuthenticatorHandle authenticator,
                                                  struct WalletKitFieldElementHandle nonce,
                                                  struct WalletKitFieldElementHandle context,
                                                  struct WalletKitFieldElementHandle blinding_factor,
                                                  struct WalletKitFieldElementHandle sub,
                                                  struct WalletKitOwnershipProofHandle *out,
                                                  struct WalletKitBuffer *out_error);

// `Authenticator.initWithDefaults`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_init_with_defaults(struct WalletKitOperationHandle operation,
                                                struct WalletKitByteSlice seed,
                                                const struct WalletKitByteSlice *rpc_url,
                                                uint8_t environment,
                                                int32_t region,
                                                struct WalletKitZkArtifactSourceHandle artifacts,
                                                struct WalletKitCredentialStoreHandle store,
                                                struct WalletKitAuthenticatorHandle *out,
                                                struct WalletKitBuffer *out_error);

// `Authenticator.initWithOhttpDefaults`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_init_with_ohttp_defaults(struct WalletKitOperationHandle operation,
                                                      struct WalletKitByteSlice seed,
                                                      const struct WalletKitByteSlice *rpc_url,
                                                      uint8_t environment,
                                                      int32_t region,
                                                      struct WalletKitZkArtifactSourceHandle artifacts,
                                                      struct WalletKitCredentialStoreHandle store,
                                                      struct WalletKitAuthenticatorHandle *out,
                                                      struct WalletKitBuffer *out_error);

// `Authenticator.initialize`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_authenticator_init(struct WalletKitOperationHandle operation,
                                  struct WalletKitByteSlice seed,
                                  struct WalletKitByteSlice config,
                                  struct WalletKitZkArtifactSourceHandle artifacts,
                                  struct WalletKitCredentialStoreHandle store,
                                  struct WalletKitAuthenticatorHandle *out,
                                  struct WalletKitBuffer *out_error);

// `InitializingAuthenticator.registerWithDefaults`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_initializing_authenticator_register_with_defaults(struct WalletKitOperationHandle operation,
                                                                 struct WalletKitByteSlice seed,
                                                                 const struct WalletKitByteSlice *rpc_url,
                                                                 uint8_t environment,
                                                                 int32_t region,
                                                                 const struct WalletKitByteSlice *recovery_address,
                                                                 struct WalletKitInitializingAuthenticatorHandle *out,
                                                                 struct WalletKitBuffer *out_error);

// `InitializingAuthenticator.registerWithOhttpDefaults`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_initializing_authenticator_register_with_ohttp_defaults(struct WalletKitOperationHandle operation,
                                                                       struct WalletKitByteSlice seed,
                                                                       const struct WalletKitByteSlice *rpc_url,
                                                                       uint8_t environment,
                                                                       int32_t region,
                                                                       const struct WalletKitByteSlice *recovery_address,
                                                                       struct WalletKitInitializingAuthenticatorHandle *out,
                                                                       struct WalletKitBuffer *out_error);

// `InitializingAuthenticator.register`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_initializing_authenticator_register(struct WalletKitOperationHandle operation,
                                                   struct WalletKitByteSlice seed,
                                                   struct WalletKitByteSlice config,
                                                   const struct WalletKitByteSlice *recovery_address,
                                                   struct WalletKitInitializingAuthenticatorHandle *out,
                                                   struct WalletKitBuffer *out_error);

// `InitializingAuthenticator.pollStatus`.
//
// Writes the binary encoding to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_initializing_authenticator_poll_status(struct WalletKitOperationHandle operation,
                                                      struct WalletKitInitializingAuthenticatorHandle authenticator,
                                                      struct WalletKitBuffer *out,
                                                      struct WalletKitBuffer *out_error);

// `EmbeddedZkArtifacts.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_embedded_zk_artifacts_new(struct WalletKitEmbeddedZkArtifactsHandle *out,
                                         struct WalletKitBuffer *out_error);

// `EmbeddedZkArtifacts.asZkArtifactSource`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_embedded_zk_artifacts_as_zk_artifact_source(struct WalletKitEmbeddedZkArtifactsHandle artifacts,
                                                           struct WalletKitZkArtifactSourceHandle *out,
                                                           struct WalletKitBuffer *out_error);

// `CachingZkArtifacts.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_caching_zk_artifacts_new(struct WalletKitStoragePathsHandle storage_paths,
                                        struct WalletKitCachingZkArtifactsHandle *out,
                                        struct WalletKitBuffer *out_error);

// `CachingZkArtifacts.asZkArtifactSource`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_caching_zk_artifacts_as_zk_artifact_source(struct WalletKitCachingZkArtifactsHandle artifacts,
                                                          struct WalletKitZkArtifactSourceHandle *out,
                                                          struct WalletKitBuffer *out_error);

// `CachingZkArtifacts.preload`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_caching_zk_artifacts_preload(struct WalletKitCachingZkArtifactsHandle artifacts,
                                            struct WalletKitBuffer *out_error);

// Completes a pending integrity preparation with the host's session. Consumes
// `signer`, including when `completion` has expired or the input is invalid.
//
// # Safety
// `token` must be readable; `signer` must satisfy its table contract.
void walletkit_request_integrity_prepared(uint64_t completion,
                                          struct WalletKitByteSlice token,
                                          uint8_t platform,
                                          struct WalletKitRequestDigestSignerCallbacks signer);

// Completes a pending integrity preparation with the ordinal of a
// `RequestIntegrityError`; unknown ordinals report `CallbackFailed`.
void walletkit_request_integrity_failed(uint64_t completion,
                                        uint8_t error);

// `VerifiedMatchToken.matchCoefficient`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_verified_match_token_match_coefficient(struct WalletKitVerifiedMatchTokenHandle token,
                                                      float *out,
                                                      struct WalletKitBuffer *out_error);

// `FlamingoMatcher.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_flamingo_matcher_new(struct WalletKitByteSlice host_url,
                                    struct WalletKitFlamingoMatcherHandle *out,
                                    struct WalletKitBuffer *out_error);

// `FlamingoMatcher.newAttested`.
//
// Consumes the callback tables, including on failure.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_flamingo_matcher_new_attested(struct WalletKitByteSlice host_url,
                                             struct WalletKitRequestIntegrityProviderCallbacks integrity_provider,
                                             struct WalletKitFlamingoMatcherHandle *out,
                                             struct WalletKitBuffer *out_error);

// `FlamingoMatcher.withMeasurements`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_flamingo_matcher_with_measurements(struct WalletKitFlamingoMatcherHandle matcher,
                                                  struct WalletKitByteSlice measurements,
                                                  struct WalletKitFlamingoMatcherHandle *out,
                                                  struct WalletKitBuffer *out_error);

// `FlamingoMatcher.dangerouslySkipMeasurements`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_flamingo_matcher_dangerously_skip_measurements(struct WalletKitFlamingoMatcherHandle matcher,
                                                              struct WalletKitFlamingoMatcherHandle *out,
                                                              struct WalletKitBuffer *out_error);

// `FlamingoMatcher.withHeaders`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_flamingo_matcher_with_headers(struct WalletKitFlamingoMatcherHandle matcher,
                                             struct WalletKitByteSlice headers,
                                             struct WalletKitFlamingoMatcherHandle *out,
                                             struct WalletKitBuffer *out_error);

// `FlamingoMatcher.performMatch`.
//
// Writes the binary encoding to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_flamingo_matcher_perform_match(struct WalletKitOperationHandle operation,
                                              struct WalletKitFlamingoMatcherHandle matcher,
                                              struct WalletKitByteSlice request,
                                              struct WalletKitBuffer *out,
                                              struct WalletKitBuffer *out_error);

// `FieldElement.fromBytes`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_field_element_from_bytes(struct WalletKitByteSlice bytes,
                                        struct WalletKitFieldElementHandle *out,
                                        struct WalletKitBuffer *out_error);

// `FieldElement.fromU64`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_field_element_from_u64(uint64_t value,
                                      struct WalletKitFieldElementHandle *out,
                                      struct WalletKitBuffer *out_error);

// `FieldElement.toBytes`.
//
// Writes the bytes to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_field_element_to_bytes(struct WalletKitFieldElementHandle element,
                                      struct WalletKitBuffer *out,
                                      struct WalletKitBuffer *out_error);

// `FieldElement.tryFromHexString`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_field_element_try_from_hex_string(struct WalletKitByteSlice hex_string,
                                                 struct WalletKitFieldElementHandle *out,
                                                 struct WalletKitBuffer *out_error);

// `FieldElement.toHexString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_field_element_to_hex_string(struct WalletKitFieldElementHandle element,
                                           struct WalletKitBuffer *out,
                                           struct WalletKitBuffer *out_error);

// `Credential.fromBytes`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_from_bytes(struct WalletKitByteSlice bytes,
                                     struct WalletKitCredentialHandle *out,
                                     struct WalletKitBuffer *out_error);

// `Credential.sub`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_sub(struct WalletKitCredentialHandle credential,
                              struct WalletKitFieldElementHandle *out,
                              struct WalletKitBuffer *out_error);

// `Credential.issuerSchemaId`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_issuer_schema_id(struct WalletKitCredentialHandle credential,
                                           uint64_t *out,
                                           struct WalletKitBuffer *out_error);

// `Credential.expiresAt`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_expires_at(struct WalletKitCredentialHandle credential,
                                     uint64_t *out,
                                     struct WalletKitBuffer *out_error);

// `Credential.associatedDataCommitment`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_associated_data_commitment(struct WalletKitCredentialHandle credential,
                                                     struct WalletKitFieldElementHandle *out,
                                                     struct WalletKitBuffer *out_error);

// `Credential.claims`.
//
// Writes the binary encoding to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_claims(struct WalletKitCredentialHandle credential,
                                 struct WalletKitBuffer *out,
                                 struct WalletKitBuffer *out_error);

// `Credential.claimsHex`.
//
// Writes the binary encoding to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_claims_hex(struct WalletKitCredentialHandle credential,
                                     struct WalletKitBuffer *out,
                                     struct WalletKitBuffer *out_error);

// `ProofRequest.fromJson`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_request_from_json(struct WalletKitByteSlice json,
                                       struct WalletKitProofRequestHandle *out,
                                       struct WalletKitBuffer *out_error);

// `ProofRequest.toJson`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_request_to_json(struct WalletKitProofRequestHandle request,
                                     struct WalletKitBuffer *out,
                                     struct WalletKitBuffer *out_error);

// `ProofRequest.id`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_request_id(struct WalletKitProofRequestHandle request,
                                struct WalletKitBuffer *out,
                                struct WalletKitBuffer *out_error);

// `ProofRequest.version`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_request_version(struct WalletKitProofRequestHandle request,
                                     uint8_t *out,
                                     struct WalletKitBuffer *out_error);

// `ProofResponse.toJson`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_response_to_json(struct WalletKitProofResponseHandle response,
                                      struct WalletKitBuffer *out,
                                      struct WalletKitBuffer *out_error);

// `ProofResponse.id`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_response_id(struct WalletKitProofResponseHandle response,
                                 struct WalletKitBuffer *out,
                                 struct WalletKitBuffer *out_error);

// `ProofResponse.version`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_response_version(struct WalletKitProofResponseHandle response,
                                      uint8_t *out,
                                      struct WalletKitBuffer *out_error);

// `ProofResponse.error`.
//
// Writes the UTF-8 string to `out`, or a null buffer when absent.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_response_error(struct WalletKitProofResponseHandle response,
                                    struct WalletKitBuffer *out,
                                    struct WalletKitBuffer *out_error);

// `OwnershipProof.encode`.
//
// Writes the bytes to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_ownership_proof_encode(struct WalletKitOwnershipProofHandle proof,
                                      struct WalletKitBuffer *out,
                                      struct WalletKitBuffer *out_error);

// `OwnershipProof.encodeB64`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_ownership_proof_encode_b64(struct WalletKitOwnershipProofHandle proof,
                                          struct WalletKitBuffer *out,
                                          struct WalletKitBuffer *out_error);

// `OwnershipProof.merkleRoot`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_ownership_proof_merkle_root(struct WalletKitOwnershipProofHandle proof,
                                           struct WalletKitFieldElementHandle *out,
                                           struct WalletKitBuffer *out_error);

// `UserAgent.headerValue`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_user_agent_header_value(struct WalletKitUserAgentHandle user_agent,
                                       struct WalletKitBuffer *out,
                                       struct WalletKitBuffer *out_error);

// `UserAgentBuilder.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_user_agent_builder_new(struct WalletKitUserAgentBuilderHandle *out,
                                      struct WalletKitBuffer *out_error);

// `UserAgentBuilder.withSegment`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_user_agent_builder_with_segment(struct WalletKitUserAgentBuilderHandle builder,
                                               struct WalletKitByteSlice name,
                                               struct WalletKitByteSlice version,
                                               struct WalletKitUserAgentBuilderHandle *out,
                                               struct WalletKitBuffer *out_error);

// `UserAgentBuilder.withAppSegmentForClient`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_user_agent_builder_with_app_segment_for_client(struct WalletKitUserAgentBuilderHandle builder,
                                                              struct WalletKitByteSlice app_version,
                                                              struct WalletKitByteSlice client_name,
                                                              struct WalletKitUserAgentBuilderHandle *out,
                                                              struct WalletKitBuffer *out_error);

// `UserAgentBuilder.withWalletkitSegment`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_user_agent_builder_with_walletkit_segment(struct WalletKitUserAgentBuilderHandle builder,
                                                         struct WalletKitUserAgentBuilderHandle *out,
                                                         struct WalletKitBuffer *out_error);

// `UserAgentBuilder.withClientSegment`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_user_agent_builder_with_client_segment(struct WalletKitUserAgentBuilderHandle builder,
                                                      struct WalletKitByteSlice client_name,
                                                      struct WalletKitByteSlice os_version,
                                                      struct WalletKitUserAgentBuilderHandle *out,
                                                      struct WalletKitBuffer *out_error);

// `UserAgentBuilder.build`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_user_agent_builder_build(struct WalletKitUserAgentBuilderHandle builder,
                                        struct WalletKitUserAgentHandle *out,
                                        struct WalletKitBuffer *out_error);

// `WalletKit.emitLog`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_emit_log(uint8_t level,
                        struct WalletKitByteSlice message,
                        struct WalletKitBuffer *out_error);

// `WalletKit.initLogging`.
//
// Consumes the callback tables, including on failure.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_init_logging(struct WalletKitLoggerCallbacks logger,
                            int32_t level,
                            struct WalletKitBuffer *out_error);

// `WalletKit.sanitizeHexSecrets`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_sanitize_hex_secrets(struct WalletKitByteSlice input,
                                    struct WalletKitBuffer *out,
                                    struct WalletKitBuffer *out_error);

// `Environment.pohRecoveryAgentAddress`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_environment_poh_recovery_agent_address(uint8_t environment,
                                                      struct WalletKitBuffer *out,
                                                      struct WalletKitBuffer *out_error);

// `Environment.worldIdVerifierAddress`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_environment_world_id_verifier_address(uint8_t environment,
                                                     struct WalletKitBuffer *out,
                                                     struct WalletKitBuffer *out_error);

// `TfhNfcIssuer.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_tfh_nfc_issuer_new(uint8_t environment,
                                  struct WalletKitByteSlice user_agent,
                                  struct WalletKitTfhNfcIssuerHandle *out,
                                  struct WalletKitBuffer *out_error);

// `TfhNfcIssuer.refreshNfcCredential`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_tfh_nfc_issuer_refresh_nfc_credential(struct WalletKitOperationHandle operation,
                                                     struct WalletKitTfhNfcIssuerHandle issuer,
                                                     struct WalletKitByteSlice request_body,
                                                     struct WalletKitByteSlice headers,
                                                     struct WalletKitCredentialHandle *out,
                                                     struct WalletKitBuffer *out_error);

// `RecoveryBindingManager.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_recovery_binding_manager_new(uint8_t environment,
                                            struct WalletKitUserAgentBuilderHandle user_agent_builder,
                                            struct WalletKitRecoveryBindingManagerHandle *out,
                                            struct WalletKitBuffer *out_error);

// `RecoveryBindingManager.newWithBaseUrl`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_recovery_binding_manager_new_with_base_url(struct WalletKitByteSlice base_url,
                                                          struct WalletKitUserAgentBuilderHandle user_agent_builder,
                                                          struct WalletKitRecoveryBindingManagerHandle *out,
                                                          struct WalletKitBuffer *out_error);

// `RecoveryBindingManager.bindRecoveryAgent`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_recovery_binding_manager_bind_recovery_agent(struct WalletKitOperationHandle operation,
                                                            struct WalletKitRecoveryBindingManagerHandle manager,
                                                            struct WalletKitAuthenticatorHandle authenticator,
                                                            struct WalletKitByteSlice sub,
                                                            struct WalletKitByteSlice recovery_agent_address,
                                                            struct WalletKitBuffer *out_error);

// `RecoveryBindingManager.unbindRecoveryAgent`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_recovery_binding_manager_unbind_recovery_agent(struct WalletKitOperationHandle operation,
                                                              struct WalletKitRecoveryBindingManagerHandle manager,
                                                              struct WalletKitAuthenticatorHandle authenticator,
                                                              struct WalletKitByteSlice sub,
                                                              struct WalletKitBuffer *out_error);

// `RecoveryBindingManager.getRecoveryBinding`.
//
// Writes the binary encoding to `out`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_recovery_binding_manager_get_recovery_binding(struct WalletKitOperationHandle operation,
                                                             struct WalletKitRecoveryBindingManagerHandle manager,
                                                             uint64_t leaf_index,
                                                             struct WalletKitBuffer *out,
                                                             struct WalletKitBuffer *out_error);

// `StoragePaths.fromRoot`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_from_root(struct WalletKitByteSlice root,
                                       struct WalletKitStoragePathsHandle *out,
                                       struct WalletKitBuffer *out_error);

// `StoragePaths.rootPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_root_path_string(struct WalletKitStoragePathsHandle paths,
                                              struct WalletKitBuffer *out,
                                              struct WalletKitBuffer *out_error);

// `StoragePaths.worldidDirPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_worldid_dir_path_string(struct WalletKitStoragePathsHandle paths,
                                                     struct WalletKitBuffer *out,
                                                     struct WalletKitBuffer *out_error);

// `StoragePaths.vaultDbPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_vault_db_path_string(struct WalletKitStoragePathsHandle paths,
                                                  struct WalletKitBuffer *out,
                                                  struct WalletKitBuffer *out_error);

// `StoragePaths.cacheDbPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_cache_db_path_string(struct WalletKitStoragePathsHandle paths,
                                                  struct WalletKitBuffer *out,
                                                  struct WalletKitBuffer *out_error);

// `StoragePaths.lockPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_lock_path_string(struct WalletKitStoragePathsHandle paths,
                                              struct WalletKitBuffer *out,
                                              struct WalletKitBuffer *out_error);

// `StoragePaths.groth16DirPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_groth16_dir_path_string(struct WalletKitStoragePathsHandle paths,
                                                     struct WalletKitBuffer *out,
                                                     struct WalletKitBuffer *out_error);

// `StoragePaths.queryZkeyPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_query_zkey_path_string(struct WalletKitStoragePathsHandle paths,
                                                    struct WalletKitBuffer *out,
                                                    struct WalletKitBuffer *out_error);

// `StoragePaths.nullifierZkeyPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_nullifier_zkey_path_string(struct WalletKitStoragePathsHandle paths,
                                                        struct WalletKitBuffer *out,
                                                        struct WalletKitBuffer *out_error);

// `StoragePaths.queryGraphPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_query_graph_path_string(struct WalletKitStoragePathsHandle paths,
                                                     struct WalletKitBuffer *out,
                                                     struct WalletKitBuffer *out_error);

// `StoragePaths.nullifierGraphPathString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_storage_paths_nullifier_graph_path_string(struct WalletKitStoragePathsHandle paths,
                                                         struct WalletKitBuffer *out,
                                                         struct WalletKitBuffer *out_error);

// `CredentialStore.newWithComponents`.
//
// Consumes the callback tables, including on failure.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_new_with_components(struct WalletKitStoragePathsHandle paths,
                                                    struct WalletKitDeviceKeystoreCallbacks keystore,
                                                    struct WalletKitAtomicBlobStoreCallbacks blob_store,
                                                    struct WalletKitCredentialStoreHandle *out,
                                                    struct WalletKitBuffer *out_error);

// `CredentialStore.storagePaths`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_storage_paths(struct WalletKitCredentialStoreHandle store,
                                              struct WalletKitStoragePathsHandle *out,
                                              struct WalletKitBuffer *out_error);

// `CredentialStore.initialize`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_initialize(struct WalletKitCredentialStoreHandle store,
                                           uint64_t leaf_index,
                                           uint64_t now,
                                           struct WalletKitBuffer *out_error);

// `CredentialStore.listCredentials`.
//
// Writes the binary encoding to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_list_credentials(struct WalletKitCredentialStoreHandle store,
                                                 const uint64_t *issuer_schema_id,
                                                 uint64_t now,
                                                 struct WalletKitBuffer *out,
                                                 struct WalletKitBuffer *out_error);

// `CredentialStore.fetchCredential`.
//
// Writes the handle to `out`, or a zero handle when absent.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_fetch_credential(struct WalletKitCredentialStoreHandle store,
                                                 uint64_t issuer_schema_id,
                                                 uint64_t now,
                                                 struct WalletKitCredentialHandle *out,
                                                 struct WalletKitBuffer *out_error);

// `CredentialStore.deleteCredential`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_delete_credential(struct WalletKitCredentialStoreHandle store,
                                                  uint64_t credential_id,
                                                  struct WalletKitBuffer *out_error);

// `CredentialStore.storeCredential`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_store_credential(struct WalletKitCredentialStoreHandle store,
                                                 struct WalletKitCredentialHandle credential,
                                                 struct WalletKitFieldElementHandle blinding_factor,
                                                 uint64_t expires_at,
                                                 const struct WalletKitByteSlice *associated_data,
                                                 uint64_t now,
                                                 uint64_t *out,
                                                 struct WalletKitBuffer *out_error);

// `CredentialStore.dangerDeleteAllCredentials`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_danger_delete_all_credentials(struct WalletKitCredentialStoreHandle store,
                                                              uint64_t *out,
                                                              struct WalletKitBuffer *out_error);

// `CredentialStore.recordActivity`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_record_activity(struct WalletKitCredentialStoreHandle store,
                                                struct WalletKitByteSlice entry,
                                                uint64_t now,
                                                uint64_t *out,
                                                struct WalletKitBuffer *out_error);

// `CredentialStore.listActivities`.
//
// Writes the binary encoding to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_list_activities(struct WalletKitCredentialStoreHandle store,
                                                const uint64_t *issuer_schema_id,
                                                uint32_t limit,
                                                uint32_t offset,
                                                struct WalletKitBuffer *out,
                                                struct WalletKitBuffer *out_error);

// `CredentialStore.activityMetadata`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_activity_metadata(struct WalletKitCredentialStoreHandle store,
                                                  uint64_t *out,
                                                  struct WalletKitBuffer *out_error);

// `CredentialStore.clearActivities`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_clear_activities(struct WalletKitCredentialStoreHandle store,
                                                 uint64_t *out,
                                                 struct WalletKitBuffer *out_error);

// `CredentialStore.destroyStorage`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_destroy_storage(struct WalletKitCredentialStoreHandle store,
                                                struct WalletKitBuffer *out_error);

// `CredentialStore.exportVaultForBackup`.
//
// Writes the bytes to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_export_vault_for_backup(struct WalletKitCredentialStoreHandle store,
                                                        struct WalletKitBuffer *out,
                                                        struct WalletKitBuffer *out_error);

// `CredentialStore.importVaultFromBackup`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_import_vault_from_backup(struct WalletKitCredentialStoreHandle store,
                                                         struct WalletKitByteSlice backup_bytes,
                                                         struct WalletKitBuffer *out_error);

// `CredentialStore.mergeVaultFromBackup`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_merge_vault_from_backup(struct WalletKitCredentialStoreHandle store,
                                                        struct WalletKitByteSlice backup_bytes,
                                                        uint64_t *out,
                                                        struct WalletKitBuffer *out_error);

// `CredentialStore.setVaultChangedListener`.
//
// Consumes the callback tables, including on failure.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_set_vault_changed_listener(struct WalletKitCredentialStoreHandle store,
                                                           struct WalletKitVaultChangedListenerCallbacks listener,
                                                           struct WalletKitBuffer *out_error);

// `CredentialStore.setActivityChangedListener`.
//
// Consumes the callback tables, including on failure.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_credential_store_set_activity_changed_listener(struct WalletKitCredentialStoreHandle store,
                                                              struct WalletKitActivityChangedListenerCallbacks listener,
                                                              struct WalletKitBuffer *out_error);

// `WalletKit.checkCredentialsAgainstProofRequest`.
//
// Writes the binary encoding to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_check_credentials_against_proof_request(struct WalletKitProofRequestHandle request,
                                                       struct WalletKitCredentialStoreHandle store,
                                                       uint64_t now,
                                                       struct WalletKitBuffer *out,
                                                       struct WalletKitBuffer *out_error);

// `AddressBook.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_address_book_new(struct WalletKitAddressBookHandle *out,
                                struct WalletKitBuffer *out_error);

// `AddressBook.generateProofContext`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_address_book_generate_proof_context(struct WalletKitAddressBookHandle address_book,
                                                   struct WalletKitByteSlice address_to_verify,
                                                   uint64_t timestamp,
                                                   struct WalletKitProofContextHandle *out,
                                                   struct WalletKitBuffer *out_error);

// `WorldId.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_world_id_new(struct WalletKitByteSlice secret,
                            uint8_t environment,
                            struct WalletKitWorldIdHandle *out,
                            struct WalletKitBuffer *out_error);

// `WorldId.generateNullifierHash`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_world_id_generate_nullifier_hash(struct WalletKitWorldIdHandle world_id,
                                                struct WalletKitProofContextHandle context,
                                                struct WalletKitUint256 *out,
                                                struct WalletKitBuffer *out_error);

// `WorldId.getIdentityCommitment`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_world_id_get_identity_commitment(struct WalletKitWorldIdHandle world_id,
                                                uint8_t credential_type,
                                                struct WalletKitUint256 *out,
                                                struct WalletKitBuffer *out_error);

// `WorldId.generateProof`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_world_id_generate_proof(struct WalletKitOperationHandle operation,
                                       struct WalletKitWorldIdHandle world_id,
                                       struct WalletKitProofContextHandle context,
                                       struct WalletKitProofOutputHandle *out,
                                       struct WalletKitBuffer *out_error);

// `WorldId.isEqualTo`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_world_id_is_equal_to(struct WalletKitWorldIdHandle world_id,
                                    struct WalletKitWorldIdHandle other,
                                    bool *out,
                                    struct WalletKitBuffer *out_error);

// `ProofContext.create`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_context_new(struct WalletKitByteSlice app_id,
                                 const struct WalletKitByteSlice *action,
                                 const struct WalletKitByteSlice *signal,
                                 uint8_t credential_type,
                                 struct WalletKitProofContextHandle *out,
                                 struct WalletKitBuffer *out_error);

// `ProofContext.newFromBytes`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_context_new_from_bytes(struct WalletKitByteSlice app_id,
                                            const struct WalletKitByteSlice *action,
                                            const struct WalletKitByteSlice *signal,
                                            uint8_t credential_type,
                                            struct WalletKitProofContextHandle *out,
                                            struct WalletKitBuffer *out_error);

// `ProofContext.newFromSignalHash`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_context_new_from_signal_hash(struct WalletKitByteSlice app_id,
                                                  const struct WalletKitByteSlice *action,
                                                  uint8_t credential_type,
                                                  struct WalletKitUint256 signal_hash,
                                                  struct WalletKitProofContextHandle *out,
                                                  struct WalletKitBuffer *out_error);

// `ProofContext.getExternalNullifier`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_context_get_external_nullifier(struct WalletKitProofContextHandle context,
                                                    struct WalletKitUint256 *out,
                                                    struct WalletKitBuffer *out_error);

// `ProofContext.getSignalHash`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_context_get_signal_hash(struct WalletKitProofContextHandle context,
                                             struct WalletKitUint256 *out,
                                             struct WalletKitBuffer *out_error);

// `ProofContext.getCredentialType`.
//
// Writes the ordinal to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_context_get_credential_type(struct WalletKitProofContextHandle context,
                                                 uint8_t *out,
                                                 struct WalletKitBuffer *out_error);

// `ProofContext.legacyNewFromPreImageExternalNullifier`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_context_legacy_new_from_pre_image_external_nullifier(struct WalletKitByteSlice external_nullifier,
                                                                          uint8_t credential_type,
                                                                          const struct WalletKitByteSlice *signal,
                                                                          bool require_mined_proof,
                                                                          struct WalletKitProofContextHandle *out,
                                                                          struct WalletKitBuffer *out_error);

// `ProofContext.legacyNewFromRawExternalNullifier`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_context_legacy_new_from_raw_external_nullifier(struct WalletKitUint256 external_nullifier,
                                                                    uint8_t credential_type,
                                                                    const struct WalletKitByteSlice *signal,
                                                                    bool require_mined_proof,
                                                                    struct WalletKitProofContextHandle *out,
                                                                    struct WalletKitBuffer *out_error);

// `ProofOutput.toJson`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_output_to_json(struct WalletKitProofOutputHandle output,
                                    struct WalletKitBuffer *out,
                                    struct WalletKitBuffer *out_error);

// `ProofOutput.getNullifierHash`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_output_get_nullifier_hash(struct WalletKitProofOutputHandle output,
                                               struct WalletKitUint256 *out,
                                               struct WalletKitBuffer *out_error);

// `ProofOutput.getMerkleRoot`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_output_get_merkle_root(struct WalletKitProofOutputHandle output,
                                            struct WalletKitUint256 *out,
                                            struct WalletKitBuffer *out_error);

// `ProofOutput.getProofAsString`.
//
// Writes the UTF-8 string to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_output_get_proof_as_string(struct WalletKitProofOutputHandle output,
                                                struct WalletKitBuffer *out,
                                                struct WalletKitBuffer *out_error);

// `ProofOutput.getCredentialType`.
//
// Writes the ordinal to `out`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_proof_output_get_credential_type(struct WalletKitProofOutputHandle output,
                                                uint8_t *out,
                                                struct WalletKitBuffer *out_error);

// `MerkleTreeProof.fromIdentityCommitment`.
//
// Blocks until the operation completes or `operation` is cancelled.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_merkle_tree_proof_from_identity_commitment(struct WalletKitOperationHandle operation,
                                                          struct WalletKitUint256 identity_commitment,
                                                          struct WalletKitByteSlice sequencer_host,
                                                          bool require_mined_proof,
                                                          struct WalletKitMerkleTreeProofHandle *out,
                                                          struct WalletKitBuffer *out_error);

// `MerkleTreeProof.fromJsonProof`.
//
// # Safety
// Arguments must follow the conventions in [`super`].
bool walletkit_merkle_tree_proof_from_json_proof(struct WalletKitByteSlice json_proof,
                                                 struct WalletKitByteSlice merkle_root,
                                                 struct WalletKitMerkleTreeProofHandle *out,
                                                 struct WalletKitBuffer *out_error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WALLETKIT_CORE_FFI_H */
