[package]
name = "uniffi-bindgen"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "uniffi-bindgen"
path = "./src/uniffi_bindgen.rs"

[dependencies]
uniffi = { workspace = true, features = ["cli"] }
