[package]
name = "walletkit-web-authenticator-poc"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
name = "walletkit_web_authenticator_poc"

[dependencies]
uniffi = { version = "0.31.2", features = ["tokio", "wasm-unstable-single-threaded"] }
walletkit-core = { path = "../../../crates/walletkit-core", default-features = false, features = ["uniffi-wasm"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
uniffi-runtime-wasm = "0.31.0-5"
