[package]
name = "wallet-kit"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "wallet-kit"


[dependencies]
thiserror = "1.0.38"


[dev-dependencies]
uniffi = { workspace = true, features = ["bindgen-tests"] }

[profile.release]
opt-level = "z"
