// Generated by uniffi-bindgen-react-native.
// Node.js wasm-bindgen targets load the WASM module synchronously from the
// generated CommonJS glue, so there is no async init function or WASM path
// import to wire up here.
export * from './generated/walletkit_core.js';
